- ioos_catalog/templates/landing.html
> Expand US IOOS abbrevation on landing page

- ioos_catalog/templates/landing.html
> Changes email

- ioos_catalog/templates/featured_maps.html
> Changes link SCCOOS on featured maps

- ioos_catalog/static/css/welcome.css
- ioos_catalog/templates/landing.html
> Adds IOOS links to welcome page

- ioos_catalog/__init__.py
> Adds version info compliant with PEP-396

- ioos_catalog/tasks/harvest.py
- requirements.txt
Part of #360.  Should now harvest NDBC datasets when using pyoos update
as well.
> Improve NDBC harvesting

- ioos_catalog/models/harvests.py
- ioos_catalog/templates/show_service.html
- ioos_catalog/views/service.py
Implements #328.  May need additional some additional UX work as table
view is rather basic.
> Adds table for past harvests to service details

- ioos_catalog/models/__init__.py
- ioos_catalog/models/metric_counts.py
- ioos_catalog/tasks/harvest.py
Partial implementation of #340.  Includes services by type, services by
RA, and datasets from RA.  Total datasets/services not included since
they can be computed from the aggregates of the aforementioned
statistics.
> Adds basic dataset/service metrics to database

- ioos_catalog/static/css/ism-style.css
- ioos_catalog/templates/show_service.html
- requirements.txt
Fixes the CO-OPS Harvesting
#360
> CO-OPS Harvesting and Table Style

- ioos_catalog/models/harvests.py
> Adds better error message for null dataset error

- ioos_catalog/models/dataset.py
- ioos_catalog/views/landing.py
> Updates landing page to show UNIQUE datasets

- ioos_catalog/templates/catalog_map.html
- ioos_catalog/views/catalog_map.py
Adds functionality to catalog map to search by variable type, thus implementing #383.
> Add catalog map variable search

- ioos_catalog/templates/catalog_map.html
- ioos_catalog/templates/services.html
- ioos_catalog/views/catalog_map.py
Adds asset type filtering to catalog map.  Implements #385.
> Add asset type to filters on catalog map

- ioos_catalog/static/js/leaflet.textpath.js
- ioos_catalog/templates/catalog_map.html
Adds a text SVG overlay for trajectories/GeoJSON LineStrings on
highlight.  Requires Leaflet.TextPath plugin.  Implements #346
> Adds text SVG arrow markers for trajectories

- ioos_catalog/tasks/reindex_services.py
Attempts to only use ERDDAP metadata links if an ERDDAP endpoint is
detected.  If non-ERDDAP DAP, try to use DAP metadata endpoint.
Addresses #324.
> Use proper metadata link for DAP sources

- ioos_catalog/models/harvests.py
Fixes an improper number of args to an exception handling function
> Adds proper number of args to new_message

- ioos_catalog/views/catalog_map.py
Adds case insensitive variable search to catalog map.  Implements #402.
> Case insensitive variable search on catalog map

- ioos_catalog/views/__init__.py
- ioos_catalog/views/metrics.py
Fixes https://github.com/ioos/catalog/issues/410
> Adds metrics view

- ioos_catalog/tasks/reindex_services.py
I saw errors piling up in the queues where it couldn't get a valid HTTP
Status Code and would crash preventing ALL services from being updated.
> Adds skips to services that can't be fetched

- Dockerfile
- config.yml
- contrib/crontab
- contrib/docker/my_init.d/52_configure
- contrib/scripts/install_captcha.sh
- contrib/scripts/install_python.sh
- contrib/scripts/manage.sh
- contrib/scripts/run_worker.sh
- ioos_catalog/tasks/reindex_services.py
- ioos_catalog/templates/base.html
- ioos_catalog/templates/landing.html
- ioos_catalog/templates/show_service.html
- ioos_catalog/views/catalog_map.py
- ioos_catalog/views/inventory.py
- ioos_catalog/views/metadata.py
- ioos_catalog/views/ra.py
- ioos_catalog/views/service.py
- manage.py
- requirements.txt
- Dockerization
- Integration with CKAN
> CKAN Integration for Service Monitor

- contrib/crontab
- ioos_catalog/tasks/harvest.py
- manage.py
Imagine my surprise when I see that it was ME that committed a cardinal
sin of hard-coding object-ids for explicit behavior.
> Remove bad code for handling large services

- ioos_catalog/harvesters/dap_harvester.py
- ioos_catalog/harvesters/sos_harvester.py
- ioos_catalog/models/harvests.py
- ioos_catalog/templates/feedback_email.txt
- ioos_catalog/util.py
- ioos_catalog/views/help.py
- Code cleanup of Dap Harvester
- More explicit exception handling and logging messages
- Better timeout support for `service.ping`
> Better Error Handling
